# Linear SVC

In [1]:
# import json
# import pandas as pd
# from sklearn import svm
# from sklearn.svm import LinearSVC
# from sklearn.datasets import make_classification
# from sklearn.preprocessing import MultiLabelBinarizer
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.feature_extraction.text import HashingVectorizer

* LinearSVC implements “one-vs-the-rest” multi-class strategy, thus training n_class models.
* An array X of size [n_samples, n_features] holding the training samples
* Array Y of class labels (strings or integers), size [n_samples]:

In [2]:
#X = [[0], [1], [2], [3], [4]]
#Y = [0, 1, 2, 3, 4]

In [3]:
#lin_clf = svm.LinearSVC()
#lin_clf.fit(X, Y) 

In [4]:
# with open('data.json') as f:
#     data = json.load(f)

Create a TfidfVectorizer for out data

In [5]:
# vectorizer = TfidfVectorizer()
# X = [
#     vectorizer.fit_transform(data['football']),
#     vectorizer.fit_transform(data['basketball']),
#     vectorizer.fit_transform(data['hockey']),
#     vectorizer.fit_transform(data['baseball']),
#     vectorizer.fit_transform(data['soccer'])
#     ]


# X = [
#         data['football'],
#         data['basketball'],
#         data['hockey'],
#         data['baseball'],
#         data['soccer']
#     ]

# Pandas vectorized column names

In [6]:
# vector = []
# Y = []
# vectorizer = HashingVectorizer(n_features=2 ** 20)
# for element in data:
#     vector.append(vectorizer.fit_transform(element))
#     for key in element.keys():
#         Y.append(key)

In [7]:
# df = pd.DataFrame(data=vector, columns=['vector'])
# df['sport'] = Y

In [8]:
# vectorizer = HashingVectorizer(n_features=2 ** 20)

In [9]:
# lin_clf = svm.LinearSVC()
# lin_clf.fit(df.vector, df.sport)

In [10]:
# Y = ['football', 'basketball', 'hockey', 'baseball', 'soccer']
# df = pd.DataFrame(data=X, index=Y)

Scikit learn must have a 2d matrix so I am filling the excess values with a blank string for now

In [11]:
# df = df.transpose()
# df.fillna(value="", inplace=True)
# df.head()

In [12]:
# vectorizer = TfidfVectorizer()
# vectorizer.fit_transform(data['football'])
# lin_clf = svm.LinearSVC()
# lin_clf.fit(vectorizer.get_feature_names(), 'football')

Vectorizer does not work with scm.LinearSVC() because some column names have numbers in them.
* Ex: ValueError: could not convert string to float: '1stdown'


# HashingVectorizer

* n_features : integer, default = (2 ** 20)
* The number of features (columns) in the output matrices. 
* Small numbers of features are likely to cause hash collisions, but large numbers will cause larger coefficient dimensions in linear learners.

In [13]:
# vectorizer = HashingVectorizer(n_features=2 ** 20)
# # X = vectorizer.fit_transform(data)
# # No longer works becasue of change in data.json

In [14]:
# lin_clf = svm.LinearSVC()
# lin_clf.fit(df.vector, df.sport)

In [15]:
# sample = {}
# sample['new'] = ['steal', 'homerun', 'strikeout']
# Z = vectorizer.fit_transform(sample)
# dec = lin_clf.decision_function(Z)

In [16]:
# dec

In [17]:
# print(X)

# Dict Vectorizer

In [18]:
#from sklearn.feature_extraction import DictVectorizer

In [19]:
# vec = DictVectorizer()
# vec.fit_transform(data).toarray()

* Dict Vectorizer does not like the shape of data.
* Data key -> value is 'sport' -> ['column names',...]

In [20]:
# df = pd.DataFrame.from_dict(data, orient='index')
# df = df.transpose()
# df.head()

In [21]:
# # 0 -> football
# # 1 -> basketball
# # 0 -> hockey
# # 0 -> baseball
# # 0 -> soccer

# X = [[0], [1], [2], [3], [4]]

In [22]:
# Y = [len(data['football']),
#      len(data['basketball']),
#      len(data['hockey']),
#      len(data['baseball']),
#      len(data['soccer'])]

In [23]:
#lin_clf = svm.LinearSVC()
#lin_clf.fit(X, Y)


In [24]:
# dec = lin_clf.decision_function([[1]])
# dec

In [25]:
# Y = [data['football'], 
#      data['basketball'], 
#      data['hockey'], 
#      data['baseball'], 
#      data['soccer']]
# Y = MultiLabelBinarizer().fit_transform(Y)

In [26]:
# lin_clf = svm.LinearSVC()
# lin_clf.fit(X, Y) 

* Research TfidfVectorizer
* https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
* lin_clf.fit() is complaining about bad input shape
* https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html

In [27]:
# from sklearn import preprocessing
# import pandas as pd
# import json

In [28]:
# # Import json file
# with open('data.json') as f:
#     data = json.load(f)

In [29]:
# # Load json file into pandas dataframe
# df = pd.read_json('data.json')
# df = df.fillna('')

In [30]:
# # Create the Labelencoder object
# le = preprocessing.LabelEncoder()

In [31]:
# # Convert the categorical columns into numeric
# encode_value = le.fit_transform(df.columns)
# encode_value

In [32]:
# # Convert the categorical columns into numeric
# for column in df.columns:
#     df[column] = le.fit_transform(df[column])

# Sci-Kit-Learn Tutorial

In [33]:
from sklearn import preprocessing
import pandas as pd
from collections import defaultdict
import json

In [34]:
# Import json file
with open('project/data.json') as f:
    data = json.load(f)

In [35]:
# Load json file into pandas dataframe
#df = pd.read_json('data.json')
#df = df.fillna('')

In [36]:
X = []
Y = []
for element in data:
    for key in element.keys():
        X.append(key)
    for value in element.values():
        Y.append(value)

In [37]:
# Reshap the dataframe to be ['sport', 'col_name']
data = pd.DataFrame(X, columns=['sport'])
data['col'] = Y
data['cop'] = data.sport

In [38]:
data.head()

sport       col       cop
0  football  playerid  football
1  football      name  football
2  football  position  football
3  football      year  football
4  football    season  football

In [39]:
# Create the Labelencoder object
le = preprocessing.LabelEncoder()

In [40]:
# Convert the categorical columns into numeric
encode_value = le.fit_transform(data.columns)
encode_value

array([2, 0, 1])

In [41]:
# Convert the categorical columns into numeric
for column in ['sport', 'col']:
    data[column] = le.fit_transform(data[column])

In [42]:
data.head()

sport   col       cop
0      2  6948  football
1      2  6851  football
2      2  6964  football
3      2  7227  football
4      2  7072  football

In [43]:
# Create a hashmap of transformed data
# {encode_val : "sport"}
sport_id = {}
for name, group in data.groupby(['sport', 'cop']):
    sport_id[name[0]] = name[1]

In [44]:
# Set the desired output into a separate dataframe
target = data.sport

In [45]:
# Remove the predictive output from the originial dataset
data = data.col

In [46]:
# Reshape data
data = data.reshape(-1, 1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


In [47]:
# Train test and split
from sklearn.model_selection import train_test_split

In [48]:
# Split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size = 0.30, random_state = 10)

## Naive Bayes

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [50]:
# Create an object of the type GaussianNB
gnb = GaussianNB()

In [51]:
# Train the algorithm on training data and predict using the testing data
pred = gnb.fit(data_train, target_train).predict(data_test)

In [52]:
print("Naive-Bayes accuracy: ", accuracy_score(target_test, pred, normalize=True))

Naive-Bayes accuracy:  0.7996733805117039


## LinearSVC

In [53]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [54]:
# Create an object of the type LinearSVC
svc_model = LinearSVC(random_state=0)

In [55]:
# Train the algorithm on training data and predict using the testing data
pred = svc_model.fit(data_train, target_train).predict(data_test)

In [56]:
print("LinearSVC accuracy: ", accuracy_score(target_test, pred, normalize=True))

LinearSVC accuracy:  0.7345309381237525


## K-Neighbors Classifier

In [57]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [58]:
# Create object of the classifier
neigh = KNeighborsClassifier(n_neighbors=3)

In [59]:
#Train the algorithm
neigh.fit(data_train, target_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [60]:
# Predict the response
pred = neigh.predict(data_test)

In [61]:
print('KNeighbors accuracy score: ', accuracy_score(target_test, pred))

KNeighbors accuracy score:  0.9718744329522773


## NB Test

In [62]:
cols = pd.read_csv('../../Downloads/MOCK_DATA_ALT_COLUMN_NAMES.csv').columns
cols

Index(['id', 'FirstName', 'LastName', 'PlayerNumber', 'TeamName',
       'PlayerPosition', 'HomeRuns'],
      dtype='object')

In [63]:
# Convert the categorical columns into numeric
encode_value = le.fit_transform(cols)
encode_value

array([6, 0, 2, 3, 5, 4, 1])

In [64]:
# Reshape data
encode_value = encode_value.reshape(-1, 1)
encode_value

array([[6],
       [0],
       [2],
       [3],
       [5],
       [4],
       [1]])

In [65]:
# Train the algorithm on training data and predict using the testing data
pred = gnb.fit(data_train, target_train).predict(encode_value)

In [66]:
sport_id[max(pred)]

'soccer'

Naive Bayes predicts soccer when it should be baseball

## LinearSVC test

In [67]:
pred = svc_model.fit(data_train, target_train).predict(encode_value)

In [68]:
sport_id[max(pred)]

'football'

Linear SVC predicts soccer when it should be baseball

## K-Nearest test

In [69]:
neigh = KNeighborsClassifier(n_neighbors=40)

In [70]:
pred = neigh.fit(data_train, target_train).predict(encode_value)

In [71]:
sport_id[max(pred)]

'football'

k-nearest predicts soccer instead of baseball

# Overall, LabelEncoder is a poor string -> integer converter
## Attempting HashingVectorizer

In [72]:
from sklearn.feature_extraction.text import HashingVectorizer

In [73]:
# Import json file
with open('project/data.json') as f:
    data = json.load(f)

In [74]:
X = []
Y = []
for element in data:
    for key in element.keys():
        X.append(key)
    for value in element.values():
        Y.append(value)

In [75]:
# Reshap the dataframe to be ['sport', 'col_name']
data = pd.DataFrame(X, columns=['sport'])
data['col'] = Y
data['cop'] = data.sport

In [76]:
data.head()

sport       col       cop
0  football  playerid  football
1  football      name  football
2  football  position  football
3  football      year  football
4  football    season  football

In [77]:
# Hashing Vectorizer
vectorizer = HashingVectorizer(n_features=2**4)
data.cop = vectorizer.fit_transform(data.col)

In [78]:
# Set the desired output into a separate dataframe
target = data.sport

In [79]:
# Remove the predictive output from the originial dataset
#data = data.cop
cop = data.cop

In [80]:
# Reshape data
cop = cop.reshape(-1, 1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


In [81]:
# Split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(cop, target, test_size = 0.30, random_state = 10)

### Naive Bayes

In [82]:
# Train the algorithm on training data and predict using the testing data
pred = gnb.fit(data_train, target_train).predict(data_test)

ValueError: setting an array element with a sequence.

### After talking with MarkLogic, we will have the user configure the uploaded datasets to confirm important column names.
* We also need to review data.json and choose important and unique column names for each sport.
* Consider using 10 column names per sport to start

In [ ]:
jsssson = {'filename': ['col1', 'col2', 'col3']}

In [ ]:
x = []
for j in jsssson.keys():
    x.append(j)

In [ ]:
print(x[0])

### Convert int64 to json serializable

In [93]:
!ls ../../../rawDataSets/baseball/baseballdatabank/BattingPost_short.csv

../../../rawDataSets/baseball/baseballdatabank/BattingPost_short.csv


In [94]:
file = '../../../rawDataSets/baseball/baseballdatabank/BattingPost_short.csv'

In [95]:
data = pd.read_csv(file)
data.dropna(inplace=True)

In [96]:
data.head(5)

yearID round   playerID teamID lgID  G  AB  R  H  2B  ...   RBI  SB   CS  \
201    1903    WS  beaumgi01    PIT   NL  8  34  6  9   0  ...     1   2  0.0   
202    1903    WS  branski01    PIT   NL  8  29  3  6   0  ...     1   1  0.0   
203    1903    WS  clarkfr01    PIT   NL  8  34  3  9   2  ...     2   1  0.0   
204    1903    WS  colliji01    BOS   AL  8  36  5  9   1  ...     1   3  0.0   
205    1903    WS  crigelo01    BOS   AL  8  26  1  6   0  ...     4   0  0.0   

     BB  SO  IBB  HBP   SH   SF  GIDP  
201   2   4    0  0.0  0.0  0.0   0.0  
202   1   6    0  0.0  1.0  0.0   0.0  
203   1   5    0  0.0  0.0  0.0   0.0  
204   1   1    0  0.0  0.0  0.0   1.0  
205   2   3    0  0.0  1.0  0.0   1.0  

[5 rows x 22 columns]

In [97]:
data.dtypes

yearID        int64
round        object
playerID     object
teamID       object
lgID         object
G             int64
AB            int64
R             int64
H             int64
2B            int64
3B            int64
HR            int64
RBI           int64
SB            int64
CS          float64
BB            int64
SO            int64
IBB           int64
HBP         float64
SH          float64
SF          float64
GIDP        float64
dtype: object

In [98]:
spec_cols = []
for col in data.columns:
    t = data[col].dtype
    if t == 'int64':
        spec_cols.append(col)
        
spec_cols

['yearID',
 'G',
 'AB',
 'R',
 'H',
 '2B',
 '3B',
 'HR',
 'RBI',
 'SB',
 'BB',
 'SO',
 'IBB']

In [99]:
import numpy as np
#for row in range(data.shape[0]):
    
player = {}    
for col in data.columns:
    if col in spec_cols:
        player[col] = int(data.iloc[0][col])
    else:
        player[col] = data.iloc[0][col]

In [100]:
player

{'2B': 0,
 '3B': 1,
 'AB': 34,
 'BB': 2,
 'CS': 0.0,
 'G': 8,
 'GIDP': 0.0,
 'H': 9,
 'HBP': 0.0,
 'HR': 0,
 'IBB': 0,
 'R': 6,
 'RBI': 1,
 'SB': 2,
 'SF': 0.0,
 'SH': 0.0,
 'SO': 4,
 'lgID': 'NL',
 'playerID': 'beaumgi01',
 'round': 'WS',
 'teamID': 'PIT',
 'yearID': 1903}

In [101]:
json.dumps(player)

'{"yearID": 1903, "round": "WS", "playerID": "beaumgi01", "teamID": "PIT", "lgID": "NL", "G": 8, "AB": 34, "R": 6, "H": 9, "2B": 0, "3B": 1, "HR": 0, "RBI": 1, "SB": 2, "CS": 0.0, "BB": 2, "SO": 4, "IBB": 0, "HBP": 0.0, "SH": 0.0, "SF": 0.0, "GIDP": 0.0}'